### ISSUE TITLE
Upgrade to Kotlin 1.5.0 and serialization 1.2.1

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#256]
When trying to upgrade to Kotlin 1.5.0, internal compiler errors are thrown when trying to process `CustomInput`. The problem seems the same as [this report on YouTrack](https://youtrack.jetbrains.com/issue/KT-46444).

However, even when removing the generic type parameter of `CustomInput`, I receive different compiler errors:

```
e: java.lang.NullPointerException
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.getSerialDescriptorExpr(SerializableIrGenerator.kt:175)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.access$getSerialDescriptorExpr(SerializableIrGenerator.kt:38)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateInternalConstructor$1.invoke(SerializableIrGenerator.kt:121)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir
```

Currently, it seems we can't upgrade to 1.5.0 yet. Once the bug report on YouTrack is resolved/released, we can try again.

An upgrade to serialization 1.2.1 will also allow to fix https://github.com/Kotlin/kotlinx.serialization/issues/1323

**Comment by Whathecode** [comment]
Trying this again with Kotlin 1.5.20 and serialization 1.2.1, I still get the same problems due to the generic parameters of `CustomInput`. 

After removing these, however, I get a new error on serializable sealed classes extending from a generic base class, e.g., `ProtocolFactoryService.Event`:

```
    @Serializable
    sealed class Event : IntegrationEvent<ProtocolService>()
```

Build error:

> org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
> write$Self (Ldk/cachet/carp/protocols/application/ProtocolFactoryService$Event;Lkotlinx/serialization/encoding/CompositeEncoder;Lkotlinx/serialization/descriptors/SerialDescriptor;)V:
>   @Lkotlin/jvm/JvmStatic;()
>     // annotable parameter count: 3 (visible)
>     // annotable parameter count: 3 (invisible)
>     @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
>     @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
>     @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 2
>    L0
>     ALOAD 0
>     LDC "self"
>     INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
>     ALOAD 1
>     LDC "output"
>     INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
>     ALOAD 2
>     LDC "serialDesc"
>     INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
>    L1
>     LINENUMBER 16 L1
>     ALOAD 0
>     CHECKCAST dk/cachet/carp/common/application/services/IntegrationEvent
>     ALOAD 1
>     ALOAD 2
>     NEW kotlinx/serialization/PolymorphicSerializer
>     DUP
>     LDC Ldk/cachet/carp/protocols/application/ProtocolFactoryService;.class
>     INVOKESTATIC kotlin/jvm/internal/Reflection.getOrCreateKotlinClass (Ljava/lang/Class;)Lkotlin/reflect/KClass;
>     INVOKESPECIAL kotlinx/serialization/PolymorphicSerializer.<init> (Lkotlin/reflect/KClass;)V
>     CHECKCAST kotlinx/serialization/KSerializer
>     INVOKEVIRTUAL dk/cachet/carp/common/application/services/IntegrationEvent.write$Self (Ldk/cachet/carp/common/application/services/IntegrationEvent;Lkotlinx/serialization/encoding/CompositeEncoder;Lkotlinx/serialization/descriptors/SerialDescriptor;Lkotlinx/serialization/KSerializer;)V
>     RETURN
>    L2
>     LOCALVARIABLE self Ldk/cachet/carp/protocols/application/ProtocolFactoryService$Event; L0 L2 0
>     LOCALVARIABLE output Lkotlinx/serialization/encoding/CompositeEncoder; L0 L2 1
>     LOCALVARIABLE serialDesc Lkotlinx/serialization/descriptors/SerialDescriptor; L0 L2 2
>     MAXSTACK = 6
>     MAXLOCALS = 3
